<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasTranslatableSlug;
use Spatie\Sluggable\SlugOptions;
use Spatie\Translatable\HasTranslations;

class CategoriaNoticia extends Model
{
    use HasFactory, HasTranslations, HasTranslatableSlug;

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::createWithLocales(['es', 'en'])
            ->generateSlugsFrom(function($model){
                return "{$model->Titulo}";
            })
            ->saveSlugsTo('Slug');
    }

    public function findBySlug($slug, $locale){
        return $this->where('Slug->'.$locale, '=', $slug)->first();
    }

    public function getRouteKeyName()
    {
        return 'Slug'; // TODO: Change the autogenerated stub
    }

    protected $table = 'categorias_noticias';

    protected $fillable = ['Titulo', 'Estado', 'Slug'];

    public $translatable = ['Titulo', 'Slug'];

    public function noticias(){
        return $this->hasMany(Noticias::class);
    }
}
